x = int(input())

match x :
    case 0 :
        print(x, "--> zero")
    case 1 :
        print(x, "--> one")
    case 2 :
        print(x, "--> two")
    case 3 :
        print(x, "--> three")
    case 4 :
        print(x, "--> four")
    case 5 :
        print(x, "--> five")
    case 6 :
        print(x, "--> six")
    case 7 :
        print(x, "--> seven")
    case 8 :
        print(x, "--> eight")
    case 9 :
        print(x, "--> nine")